const WEBP_SUPPORTED =
    typeof document !== 'undefined' &&
    document.createElement('canvas').toDataURL('image/webp').startsWith('data:image/webp');

/** Prefer WebP when the browser supports it (generated by scripts/optimize-house-assets.mjs). */
export function preferWebpAsset(pngPath: string): string {
    if (!WEBP_SUPPORTED || !pngPath.endsWith('.png')) {
        return pngPath;
    }
    return pngPath.replace(/\.png$/, '.webp');
}

export function houseAssetSources(pngPath: string): { webp: string; png: string } {
    return {
        webp: pngPath.replace(/\.png$/, '.webp'),
        png: pngPath,
    };
}
